apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: sample-app
spec:
  sourceRef:
    kind: GitRepository
    name: sample-app
  interval: 5m
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        An automated update from FluxBot
        [ci skip]
